apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: bitbucket
secretGenerator:
- name: mysql-root-pass
  namespace: bitbucket
  literals:
  - password=123456
- name: mysql-user-pass
  namespace: bitbucket
  literals:
  - password=123456
resources:
  - namespace.yaml
  - mysql.yaml
  - bitbucket.yaml
